Dream Texture: UI Changes
carson-katri/dream-textures pull request #39
Opened 2022-09-20 05:02 UTC by blastframe

![image](https://user-images.githubusercontent.com/3729547/191171456-2f36a393-1d56-46de-b9b2-450f59984209.png)

- Changed UI from what was a tedious three-click process to generate a new Dream Texture image to a one-click process.
- "Dream Texture" text was very wide in the Image Editor & Node Editor menus & hard to access, now in collapsible sidebar
- Organized UI module into folder
- Assigned more appropriate History icon
- Smaller UI tweaks

2022-09-20 20:12 UTC, carson-katri requested changes
This looks really nice, thanks for the contribution! I had a few suggestions, let me know what you think.

2022-09-20 20:12 UTC, carson-katri commented on __init__.py
> +    "author": "Carson Katri, Kevin C. Burke",
If this should include all contributors, can you include Greg Richardson (@gregnr)?

```suggestion
    "author": "Carson Katri, Greg Richardson, Kevin C. Burke",
```

2022-09-20 20:12 UTC, carson-katri commented on ui/panel.py
> +    row.operator("shade.dream_texture", icon="PLAY", text="GO")
```suggestion
    row.operator("shade.dream_texture", icon="PLAY", text="Generate")
```

2022-09-20 21:02 UTC, blastframe commented
Thank you @carson-katri for the feedback and incredible add-on! I've accepted the changes you requested.

2022-09-20 21:03 UTC, blastframe commented
Oops, I accidentally closed it. It should be ready to merge!

2022-09-21 14:08 UTC, carson-katri commented
Thanks for the extra fixes!

2022-09-21 14:08 UTC, merged