Checkpoint File Import
carson-katri/dream-textures pull request #413
Opened 2022-12-07 23:01 UTC by carson-katri

This adds support for model conversion from original Stable Diffusion checkpoints to the diffusers' format.

A progress bar was also added when downloading a model from HF.

https://user-images.githubusercontent.com/13581484/206315588-a6b46dfa-d22f-4964-bb43-2e9a10531ea7.mov

2022-12-08 01:30 UTC, carson-katri commented
Ok, should be good to go now. The v2-base won't work with the `v2-inference-v` config definition, so I added an override to specify the model config manually in the import window.

2022-12-11 16:15 UTC, NullSenseStudio requested changes
Working great! Just has a couple of small issues I ran into.

2022-12-11 16:15 UTC, NullSenseStudio commented on generator_process/actor.py
> +>>>>>>> fcafd8ba4c66b5123ac63f9f07190ab1f1fd17ce
Seems something went wrong when merging, and this import is otherwise unused.
```suggestion
```

2022-12-11 16:15 UTC, NullSenseStudio commented on generator_process/actions/convert_original_stable_diffusion_to_diffusers.py
> +    global_step = checkpoint["global_step"]
A custom checkpoint I imported doesn't have this.
```suggestion
    global_step = checkpoint.get("global_step", None)
```

2022-12-11 16:15 UTC, NullSenseStudio commented on generator_process/actions/convert_original_stable_diffusion_to_diffusers.py
> +        and original_config["model"]["params"]["parameterization"] == "v"
Goes with previous suggestion.
```suggestion
        and original_config["model"]["params"]["parameterization"] == "v"
        and global_step is not None
```

2022-12-11 17:21 UTC, merged