Public Backend API
carson-katri/dream-textures pull request #654
Opened 2023-04-28 18:30 UTC by carson-katri

Closes #604 

The API is slightly different than it that PR. You can see an example of a backend in `diffusers_backend.py`, which is the default Dream Textures backend.

```python
class MyCustomBackend(Backend):
    name = "My Backend Name"
    description = "A short description of this backend"

    custom_optimization: BoolProperty(name="My Custom Optimization")

    def list_models(self, context) -> List[Model]:
        return [...]

    def list_schedulers(self, context) -> List[str]:
        return [...]

    def generate(self, task: Task, model: Model, prompt: Prompt, size: Tuple[int, int] | None, seed: int, steps: int, guidance_scale: float, scheduler: str, seamless_axes: SeamlessAxes, step_preview_mode: StepPreviewMode, iterations: int, step_callback: StepCallback, callback: Callback):
        match task:
            case PromptToImage():
                ...
            case ImageToImage(image=image, strength=strength, fit=fit):
                ...
            case Inpaint(image=image, fit=fit, strength=strength, mask_source=mask_source, mask_prompt=mask_prompt, confidence=confidence):
                ...
            case DepthToImage(depth=depth, image=image, strength=strength):
                ...
            case Outpaint(image=image, origin=origin):
                ...
            case _:
                raise NotImplementedError()

    def draw_speed_optimizations(self, layout, context):
        layout.prop(self, "custom_optimization")
```

A backend could be as simple as a single file Blender add-on, so I'm considering adding a folder to this repo to contain scripts for additional backends that would be maintained by different community members. This could contain backends for sources like Automatic1111, DreamStudio, InvokeAI, StableHorde, etc.

2023-05-19 17:36 UTC, NullSenseStudio commented
Looks like you've accidentally pushed the packaged CoreML backend in https://github.com/carson-katri/dream-textures/pull/654/commits/47118a07267bdb8b20b20d3a09e1ad8f4be1bda4

2023-05-21 19:42 UTC, carson-katri commented
Should be fixed now.

2023-07-07 16:18 UTC, carson-katri commented
Basic image generation is working. Here's a list of features that need to be tested/updated:
- [x] Prompt to image
- [ ] Image to image
- [ ] Inpainting
- [ ] Depth to image
- [ ] ControlNet
- [ ] Texture Projection
- [ ] Nodes
- [ ] Render Pass
- [ ] Upscaling

2023-07-08 20:44 UTC, Made-0f-Ice commented
I just tried to test this tool, I have "automatic1111" server running on 127.0.0.1:7860 (working via web-interface), but on the "Dream" panel in Blender I see only "Huggingface Diffusers" backend and no available models… (I'm on Debian Linux)
Does this approch yet to implement or I've made some error configuring?
Thank you in advance. I'm not hurry or so, I'm just interested in this feature.

2023-07-08 22:20 UTC, carson-katri commented
This PR doesn’t add an Automatic1111 backend, it just makes it possible for one to be created in the future.

2023-08-07 05:58 UTC, macronomicus commented
So you dont plan to use ckpt/safetensors files, but rather allow for other backend? Is there performance loss with those types? Or just too much refactoring? I've read a few posts & was curious. 

I had dreamtexture installed on last pc but have yet to dive back in on new setup, im glad you're still progressing & its looking great, blender is by far my favorite app. It'd be nice to use our model files from automatic1111, but regardless Dreamtextures stands on its own without it. I am fine with the two being separate, its simple enough to jump back & forth between them with stuff. But you're showing such great & deeper integrations its very tempting!

I imagine blender official will get in on the ai stuff too, its all still fast moving but at some point you might get some official specialized blender api stuff to work with too. Im keeping an eye out for when they start talking more ai.

2023-08-14 21:09 UTC, carson-katri commented
@macronomicus Diffusers added a new [`from_single_file`](https://huggingface.co/docs/diffusers/main/en/api/pipelines/stable_diffusion/text2img#diffusers.StableDiffusionPipeline.from_single_file) loader, which can load `.ckpt`/`safetensor` files. With that we may be able to easily support separate lookup directories for single-file models.

2023-08-20 20:48 UTC, NullSenseStudio commented
I'll take a crack at adding `from_single_file` since I'm already handling related code in #703

2023-09-14 17:16 UTC, NullSenseStudio requested changes

2023-09-17 20:33 UTC, carson-katri commented on generator_process/models/optimizations.py
> +        except: pass
@NullSenseStudio Feel free to take it

2023-09-17 21:03 UTC, carson-katri commented on property_groups/dream_prompt_validation.py
>  def validate(self, context, task: ModelType | None = None) -> bool:
Should only be in the backend now, unless its something that the backend cannot validate (like selected faces for projection).

2023-09-17 23:05 UTC, NullSenseStudio commented
Took a bit more than I thought to fix VAE tiling. It's a bit of a mess with how it's juggling the image between torch and numpy, but it's functional for now. I'll get that in better order soon since I have some changes planned for VAE tiling.

Outpainting sort of works, but the outpainted regions remain black. Seems to be caused by changes made to the inpaint pipeline. You can color a portion of an image then mark that area for inpainting, and it will still resemble that color after inpainting now.

2023-09-17 23:08 UTC, carson-katri commented
Could the `strength` value be incorrect, so it takes some of the black into account?

2023-09-17 23:32 UTC, NullSenseStudio commented
That was it!

2023-09-17 23:32 UTC, NullSenseStudio approved these changes

2023-09-18 00:31 UTC, merged

2024-11-14 11:43 UTC, TimWolfram commented
@carson-katri 

> This PR doesn’t add an Automatic1111 backend, it just makes it possible for one to be created in the future.
> 
> Contributions for new backends would be welcome once this is merged!

Has nobody implemented an A1111 backend yet? I can't find any mentions of it existing but considering it's been a year now since the backend API and A1111 is the most popular way to use stable diffusion, I'd assume someone would have implemented it by now. If not, I can try to implement it myself but I thought I might ask here before wasting my time.

2024-11-18 20:52 UTC, carson-katri commented
@TimWolfram As far as I know, no one has built an A1111 backend yet. But I'd be happy to answer any questions you have if you build one.