Various UI Tweaks
carson-katri/dream-textures pull request #659
Opened 2023-05-06 20:44 UTC by NullSenseStudio

- When there are multiple image editors, generating from an open source image or upscaling will now pick the image from the image editor it was executed from.
- Image editors with image pin activated will no longer be replaced with generated images.
- Cancel generator operator has been slightly changed to better differentiate it from release generator.
![blender_nFIlZtKP8q](https://user-images.githubusercontent.com/47096043/236645873-e79f3867-79ae-4057-9747-6413b9c5ce78.gif)
- Image texture nodes will now fill the shader editor view better instead of just the bottom right corner.
![blender_NpISzg732d](https://user-images.githubusercontent.com/47096043/236645879-56d6a80d-1e2b-44ca-b182-06c87c1b24b0.gif)

2023-05-17 17:47 UTC, NullSenseStudio commented on operators/dream_texture.py
> -        bpy.types.Scene.dream_textures_progress = bpy.props.IntProperty(name="", default=0, min=0, max=generated_args['steps'], update=step_progress_update)
I've found it's more performant to put similar functionality within the step callback. Strangely changing this to an empty function would still allow the UI to redraw. I assume it was redrawing more than necessary for seeing the progress bar. Allows for generating about 15%-20% faster in my experience.

2023-05-21 19:53 UTC, carson-katri requested changes
Nice improvements. Just one small change for img2img.

2023-05-21 19:53 UTC, carson-katri commented on operators/dream_texture.py
> +            get_source_image(context, generated_args['init_img_src'])
```suggestion
            init_image = get_source_image(context, generated_args['init_img_src'])
```

2023-05-26 17:10 UTC, carson-katri approved these changes

2023-07-02 14:36 UTC, merged